issue/hitide-ui-48: help catch collection resolution errors
podaac/hitide-ui pull request #53
Opened 2024-02-13 18:37 UTC by jbyrne6

### Changes
- Trying to catch cases of resolution being "Not Applicable" to a collection vs when there is an "Issue Loading Resolution".
- Need to try and find a collection where an error occurs so I can test the error handling.

### Related Issues
- #48

2024-02-14 00:39 UTC, frankinspace commented
So, the logic here is:

if the cmr key `[Collection]/SpatialExtent/HorizontalSpatialDomain/ResolutionAndCoordinateSystem` exists, look for the `GenericResolutions` key. If `GenericResolutions` is found, use that information to render the resolution label in the UI. If `GenericResoultions` key does not exists, then that is an unexpected error and we render "Issue Loading Resolution" in the UI.

if the cmr key `[Collection]/SpatialExtent/HorizontalSpatialDomain/ResolutionAndCoordinateSystem` does not exist: assume this was intentionally left out, render "Not Applicable" for the resolution label in the UI.

I think that makes sense to me but would appreciate @jjmcnelis opinion as well.

2024-02-15 00:04 UTC, jbyrne6 commented on src/jpl/utils/SearchDatasets.js
> +                    // resolution not applicable
Yes you are correct. This comment was added before I changed made a change to the code.

2024-02-15 00:33 UTC, frankinspace approved these changes

2024-02-15 00:34 UTC, jamesfwood approved these changes

2024-02-15 02:46 UTC, jjmcnelis commented
> So, the logic here is:
> 
> if the cmr key `[Collection]/SpatialExtent/HorizontalSpatialDomain/ResolutionAndCoordinateSystem` exists, look for the `GenericResolutions` key. If `GenericResolutions` is found, use that information to render the resolution label in the UI. If `GenericResoultions` key does not exists, then that is an unexpected error and we render "Issue Loading Resolution" in the UI.
> 
> if the cmr key `[Collection]/SpatialExtent/HorizontalSpatialDomain/ResolutionAndCoordinateSystem` does not exist: assume this was intentionally left out, render "Not Applicable" for the resolution label in the UI.
> 
> I think that makes sense to me but would appreciate @jjmcnelis opinion as well.

@frankinspace and @jbyrne6 -- Thanks for the opportunity to review. This logic described in your comment is appropriate, IMO. (So the only time we should see "Issue Loading Resolution" is in the rare case where a dataset has an alternative representation is given under HorizontalDataResolution subfield, e.g. https://cmr.earthdata.nasa.gov/search/collections.umm_json?provider=POCLOUD&ShortName=SEAGLIDER_GUAM_2019 and datasets with that characteristic are not likely to be in supported in hitide.)

2024-02-15 19:26 UTC, sliu008 requested changes
we still need the read_collection.py file

2024-02-16 23:38 UTC, merged